version: '3'
services:
  web:
    build: .
    command: bash -c "rm -f /myapp/tmp/pids/server.pid & bundle exec rails s -b 0.0.0.0 -p 3000 & bin/webpack-dev-server"
    environment:
      - PGHOST=db
      - PGUSER=dinhduc
    volumes:
      - .:/myapp
      - /myapp/node_modules
      - bundle_path:/bundle
    ports:
      - 3000:3000
    tty: true
    stdin_open: true
    depends_on:
      - db

  db:
    image: postgres:11.1
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=blog_dev
      - POSTGRES_USER=dinhduc
      - POSTGRES_PASSWORD=dinhduc
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  bundle_path:
    driver: local
  postgres-data:
    driver: local
